### ISSUE TITLE
Quitting druid results in traceback

### ISSUE THREAD

**Issue by jlmitch5** [monome/druid#12]
druid version (latest devel https://github.com/monome/druid/commit/0a34aa31706b066fcda4bf279977fa90a961d358)

python version 3.7.4 (osx)
asyncio version:

```Collecting asyncio
  Downloading https://files.pythonhosted.org/packages/22/74/07679c5b9f98a7cb0fc147b1ef1cc1853bc07a4eb9cb5731e24732c5f773/asyncio-3.4.3-py3-none-any.whl (101kB)```

after typing q to exit the repl:

```
druid ➤ python3 druid.py                                            git:master*
bye.
Traceback (most recent call last):
  File "druid.py", line 196, in <module>
    main()
  File "druid.py", line 190, in main
    loop.run_until_complete(background_task)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/base_events.py", line 579, in run_until_complete
    return future.result()
concurrent.futures._base.CancelledError
```

**Comment by trentgill** [comment]
i see this too, but i don't know enough about python (and asyncio) to understand what it means / how to fix it. (druid is my first python application!)
