### ISSUE TITLE
Can't select text

### ISSUE THREAD

**Issue by simonvanderveldt** [monome/druid#20]
Not sure why but I'm unable to select any text in the druid REPL.

I'm not sure it matters, but I'm on Linux, specifically using GNOME terminal.

**Comment by csboling** [comment]
Interestingly this does work on Windows using cmd, powershell, or "git bash" (MSYS2). 
[Reported](https://llllllll.co/t/crow-help-general-connectivity-device-qs-ecosystem/25866/419) to be broken in iTerm or VSCode's terminal on Mac.

**Comment by jlmitch5** [comment]
The note on vscode and iTerm not allowing you to select text was mine.  I will note I could sometimes get selection to workin in iTerm by switching the workspace to a different desktop and back but it would stop allowing text selection midway

**Comment by jlmitch5** [comment]
Here's a video of what I'm seeing (iTerm, macOS, zsh)

Selection can sometimes happen, but I can't figure out when selection will work and when it won't (seems to happen regardless of if you try to start your selection on a word or at the edge of the output)

Interestingly, it seems like when I am able to select, it's like the selection "scrolls" with me.  When I use cat and try to select the selection stays put while you scroll (what you'd expect).  Maybe that point would be useful for finding the bug...gonna search to see?

https://ezgif.com/video-to-gif/ezgif-1-ccb8fdb0d700.mov

**Comment by joeweiss** [comment]
I added a PR that fixes the issue, but does so by disabling the mouse support. Apparently this is an issue with `prompt-toolkit`. 

Any idea what the mouse support is used for, other than scrolling back up through the script output?
