### ISSUE TITLE
update setup details in `README`

### ISSUE THREAD

**Issue by pq** [monome/druid#22]
notably, this advice appears stale:

```
source Scripts/activate
```

and maybe `setup.sh` too?

perhaps just fly in the setup notes from https://monome.org/docs/crow/scripting/ ?

/cc @trentgill @dndrks

**Comment by trentgill** [comment]
Paging @csboling on this. I don’t know how Source works, and i’m unsure if the old docs (and those in scripting.md) will continue to work?

**Comment by trentgill** [comment]
Closing this now, but feel free to open a new issue if there's more to be done with the setup / install / library management.

**Comment by pq** [comment]
Thanks!
