### ISSUE TITLE
Uploading and downloading via the command-line

### ISSUE THREAD

**Issue by simonvanderveldt** [monome/druid#24]
Was wondering how we want to handle uploading and downloading of scripts via the command-line.
Currently there are two simple scripts that do this, that need to be called like `python3 ./upload.py`, not entirely ideal.

Do we want to roll this into the main druid script so it could become something like
```
$ druid upload scriptname.lua
```
Or do we want to keep these as separate tools (`druid-upload` and `druid-download` maybe)?

**Comment by trentgill** [comment]
Commented on PR #25 about this.

I'm inclined toward abandoning them, and your suggestion of having it handled by `druid` itself with special command-line args seems like a fantastic solution.

**Comment by simonvanderveldt** [comment]
> I wonder if it's easy / possible / worthwhile to add druid-upload and druid-download to the PATH as well? That said, I wonder if they are necessary at all. Does the ease of not needing to type u <filename> or p inside of druid surpass the potential confusion of having the separate python programs? I'm leaning toward just-one-tool-that-does-those-things.

@trentgill Yeah, agreed. I think a single tool for direct interaction with crow would be the better/clearer option.
