### ISSUE TITLE
install instructions

### ISSUE THREAD

**Issue by trentgill** [monome/druid#4]
setup requires `pip`: `apt install python-pip`
`readline` requires ncurses libs: `apt-get install libncurses5-dev`

**Comment by simonvanderveldt** [comment]
I think this has been addressed by https://github.com/monome/docs/pull/138, https://github.com/monome/docs/pull/142 and 
 https://github.com/monome/docs/pull/144 ?

**Comment by trentgill** [comment]
agreed, this is a stale issue. closing.
