### ISSUE TITLE
No newline in sublime on Windows10 causes upload failure

### ISSUE THREAD

**Issue by trentgill** [monome/druid#63]
`[string "eval"]:13: 'end' expected (to close 'function' at line 11) near <eof>`

See report here: https://llllllll.co/t/crow-druid-scripts/25974/36

**Comment by simonvanderveldt** [comment]
@trentgill Any idea why crow/the lua environment on crow needs this?
Or is this a generic lua issue, that it will only process/evaluate complete lines (ie lines that have `/n` at the end) or something like that?

**Comment by csboling** [comment]
Crow scans for a newline to decide when to pass a chunk to the evaluator. Seems like it should work to also do this when `^^w` or `^^e` are received?

**Comment by trentgill** [comment]
I see it now. It's because the parser expects a `\0` or `\n` or `\r` to end a received line. Until that char is received, the received bytes sit in a buffer inside of lib/caw.c (called `reader`).

We could either rely on @csboling 's solution here, or add some kind of buffer-flush on `^^e` or `^^w`. I'm tempted to just leave as is here & say "crow requires a terminating character at the end of an upload", but I'm willing to reconsider if we can elegantly have crow do it internally?
