### ISSUE TITLE
REPL input not visible with light theme

### ISSUE THREAD

**Issue by daveriedstra** [monome/druid#70]
The text input in the druid REPL is unreadable on a light background, which makes the whole REPL difficult to use.

![image](https://user-images.githubusercontent.com/3504098/118684008-d7b4dd80-b7cf-11eb-98c0-167d6baf0d50.png)

*(image shows issue on kitty terminal; there is text in the input)*

It looks like the REPL has some colours hardcoded in, maybe a possible solution is to support an environment variable or flag to use the terminal colour scheme?

**Comment by tehn** [comment]
fixed #72
