### ISSUE TITLE
windows always shows connected

### ISSUE THREAD

**Issue by trentgill** [monome/druid#75]
regardless of whether a crow is attached, windows druid always shows 'crow connected'.

when i attached a crow to an open druid session, it printed some startup info, but did not allow me to speak with crow (or at least, i didn't see responses to print msgs).

perhaps the serial port matching is just grabbing any open COM port (i had an FTDI debugger attached)? unsure, but it requires a little work to test on windows.

**Comment by tehn** [comment]
fixed by #76
