### ISSUE TITLE
`^^help` does not work

### ISSUE THREAD

**Issue by tyleretters** [monome/druid#77]
```
> ^^help
repl:1: unexpected symbol near '^'
```

i tried to dig into this but quickly was in over my head. i'm on `v3.0.1`.

**Comment by trentgill** [comment]
`^^help` is not a valid crow command. it appears that it was added to the list of crow commands [here](https://github.com/monome/druid/blob/c83b624feb5cd50bf0da4392219aff5e3cd459b3/src/druid/repl.py#L152), so the help text is being rather... unhelpful.

probably as simple as removing from this list.

to get druid's help menu, you just type `h` (which is printed on the first line when opening a new druid session).

**Comment by goonzoid** [comment]
Looks like this was resolved a while ago and can be closed 🌈
