### ISSUE TITLE
cli command to manage imports in lua code

### ISSUE THREAD

**Issue by joanofxyz** [monome/druid#80]
I've been playing with making different types of sequencers for the crow and have found myself repeating quite a bit of code. I was hoping there could be a function that would allow for better code modularity, rounding up all the imports from the file you're trying to upload and constructing a single composite file that can be fed to the crow.

I have been getting familiar with the codebase and I think I could make something that works, but I would like to ask first if this would be a welcome feature or if it's something that was thought of already and discarded for some specific reason.

**Comment by goonzoid** [comment]
I've been wondering about something like this as well. I can certainly imagine making use of such functionality.

**Comment by trentgill** [comment]
i like the idea, but getting the workflow right could be quite challenging. the lua implementation on crow doesn't have full `import` or `require` semantics (or rather, it only works with code baked into the firmware), so you'd just need to create global functions, or a global table with the functions inside.

the big challenge is in what commands you would need to type to make it work. it could be some kind of special token in a lua comment in your script, but then you have to do parsing of the script-to-be-uploaded. and it gets a little hairy once you start hitting the script-length or RAM limitations of the microcontroller -- more difficult to know what code is actually running on your device.

i think the original reasoning behind not supporting this kind of thing was something like: crow scripts are short, so it should be ok to manage the entire script in a single file.

if someone wants to take a crack at it i'd definitely be open to including it in the official release. perhaps a good starting point would be to write up the spec / workflow here, and we can say more definitively if it fits with the crow / druid workflow envisioned. (ie. don't build the whole thing before we're confident it's the right decision for the platform).
